Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,21 +16,19 @@ jobs:
             crtx_resp=$(curl -v "${CORTEX_API_URL}/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \
               -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" \
               -H "Authorization: ${CORTEX_API_KEY}")
-              
-              if [ -z "$crtx_resp" ]; then
-                  echo "Error: No response from API"
-                  exit 1
-              fi
-              
-              crtx_url=$(echo "$crtx_resp" | jq -r .signed_url)
-              if [ -z "$crtx_url" ]; then
-                  echo "Error: signed_url not found in the response"
-                  exit 1
-              fi
-              
-              curl -o cortexcli "$crtx_url"
-            crtx_url=$(echo $crtx_resp | jq -r ".signed_url")
-            curl -o cortexcli $crtx_url
+
+            if [ -z "$crtx_resp" ]; then
+                echo "Error: No response from API"
+                exit 1
+            fi
+
+            crtx_url=$(echo "$crtx_resp" | jq -r .signed_url)
+            if [ -z "$crtx_url" ]; then
+                echo "Error: signed_url not found in the response"
+                exit 1
+            fi
+
+            curl -o cortexcli "$crtx_url"
             chmod +x cortexcli
             ./cortexcli --version
 
